#!/usr/bin/env python
from __future__ import annotations

import argparse
import asyncio
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.render_topic_editor_pack_html import render_html
from src.features.summarising.topic_editor_agentic import assess_topic_editor_pack
from src.features.summarising.topic_editor_agentic import replay_topic_editor_scenario


REPO_ROOT = Path(__file__).resolve().parents[1]


def _slug_now(prefix: str) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return f"{prefix}_{stamp}"


def _read_json_from_stdout(stdout: str) -> dict:
    start = stdout.find("{")
    end = stdout.rfind("}")
    if start < 0 or end < start:
        raise RuntimeError(f"freeze script did not emit JSON:\n{stdout}")
    return json.loads(stdout[start:end + 1])


def _load_env_file(path: str) -> None:
    env_path = Path(path).expanduser()
    if not env_path.exists():
        return
    for raw_line in env_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'\"")
        if key and key not in os.environ:
            os.environ[key] = value


def _write_real_window_scenario(path: Path, *, name: str, guild_id: int, start: str, end: str, fixture_dir: Path) -> None:
    brief_path = path.parent / "briefs" / f"{name}.md"
    brief_path.parent.mkdir(parents=True, exist_ok=True)
    brief_path.write_text(
        "You are reviewing a real BNDC message window from the last 12 hours.\n\n"
        "Publish only source-backed updates that are useful as Discord editorial content. "
        "Keep the draft short. Prefer multiple focused cards over one large body of text. "
        "Each card should introduce one point and attach only the media or references that directly support it. "
        "Validate, preview, revise if needed, and submit only after the preview is clean.\n"
    )
    scenario = {
        "name": name,
        "tier": "real_data",
        "description": "Rolling real-data topic-editor replay generated by scripts/run_topic_editor_real_window.py.",
        "brief": f"briefs/{name}.md",
        "target_orchestrator": "topic_editor_replay",
        "priming": {
            "window": {
                "guild_id": guild_id,
                "start": start,
                "end": end,
            },
            "fixtures": {
                "window_path": str(fixture_dir),
            },
        },
        "assessment": {
            "universal_checks": True,
            "expected_final_action": "allow_editorial_judgment",
        },
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(scenario, sort_keys=False))


def _freeze_window(args: argparse.Namespace, fixture_name: str) -> dict:
    command = [
        sys.executable,
        str(REPO_ROOT / "scripts" / "freeze_topic_editor_window.py"),
        "--guild-id",
        str(args.guild_id),
        "--last-hours",
        str(args.last_hours),
        "--name",
        fixture_name,
        "--limit",
        str(args.limit),
        "--out-root",
        str(Path(args.out_root).expanduser().resolve() / "fixtures"),
    ]
    for env_file in args.env_file or []:
        command.extend(["--env-file", env_file])
    completed = subprocess.run(command, cwd=REPO_ROOT, check=False, text=True, capture_output=True)
    if completed.returncode != 0:
        raise RuntimeError(
            "failed to freeze real topic-editor window\n"
            f"command: {' '.join(command)}\n"
            f"stdout:\n{completed.stdout}\n"
            f"stderr:\n{completed.stderr}"
        )
    return _read_json_from_stdout(completed.stdout)


def main() -> None:
    parser = argparse.ArgumentParser(description="Freeze, replay, assess, and render a real rolling topic-editor window.")
    parser.add_argument("--guild-id", type=int, default=1076117621407223829)
    parser.add_argument("--last-hours", type=float, default=12)
    parser.add_argument("--actor", choices=["mock", "deepseek"], default="deepseek")
    parser.add_argument("--model", default="deepseek-v4-pro")
    parser.add_argument("--limit", type=int, default=1000)
    parser.add_argument("--out-root", default="/tmp/topic-editor-real-window")
    parser.add_argument("--env-file", action="append", default=[str(Path.home() / ".hermes" / ".env")])
    args = parser.parse_args()
    for env_file in args.env_file or []:
        _load_env_file(env_file)

    run_name = _slug_now("real_last12h")
    out_root = Path(args.out_root).expanduser().resolve()
    scenario_path = out_root / "scenarios" / f"{run_name}.yaml"
    run_dir = out_root / "runs" / run_name
    fixture = _freeze_window(args, run_name)
    fixture_dir = Path(fixture["fixture_dir"]).resolve()
    _write_real_window_scenario(
        scenario_path,
        name=run_name,
        guild_id=args.guild_id,
        start=fixture["start"],
        end=fixture["end"],
        fixture_dir=fixture_dir,
    )

    summary = asyncio.run(
        replay_topic_editor_scenario(
            scenario_path,
            run_dir,
            actor_kind=args.actor,
            mock_actor=args.actor == "mock",
            model=args.model,
        )
    )
    assessment = assess_topic_editor_pack(run_dir)
    index = render_html(out_root / "runs", out_root / "runs" / "index.html")
    print(json.dumps({
        "scenario": str(scenario_path),
        "fixture_dir": fixture["fixture_dir"],
        "run_dir": str(run_dir),
        "html": str(index),
        "summary": summary,
        "assessment": assessment,
    }, indent=2, sort_keys=True, default=str))


if __name__ == "__main__":
    main()
